[General]
showTray=false
telemetry=false

[albert]
global_handler_enabled=false

[applications]
enabled=true
terminal=com.mitchellh.ghostty

[caffeine]
default_timeout=60
enabled=true
global_handler_enabled=false

[calculator_qalculate]
enabled=true

[clipboard]
enabled=true

[datetime]
enabled=true

[docs]
enabled=true
global_handler_enabled=false

[files]
enabled=true
paths=@Invalid()

[hash]
enabled=true

[pluginregistry]
global_handler_enabled=false

[python]
enabled=true

[python.color]
enabled=true

[python.docker]
enabled=true

[python.emoji]
enabled=true
global_handler_enabled=false
use_derived=true

[ssh]
enabled=false

[system]
enabled=true
hibernate_enabled=false
lock_enabled=false
suspend_enabled=false
title_poweroff=Shutdown

[timer]
enabled=true

[timezones]
enabled=true

[widgetsboxmodel]
alwaysOnTop=true
clearOnHide=false
clientShadow=false
darkTheme=Default System Palette
displayScrollbar=false
followCursor=true
hideOnFocusLoss=true
historySearch=true
itemCount=5
lightTheme=Numix
quitOnClose=false
showCentered=true
systemShadow=false
