#              _
#             | |
#      _______| |__  _ __ ___
#     |_  / __| '_ \| '__/ __|
#    _ / /\__ \ | | | | | (__
#   (_)___|___/_| |_|_|  \___|

export DOTFILES="$HOME/.dotfiles"
export SPELLS="$HOME/.spells"

export HISTSIZE=100000
export SAVEHIST=100000
export HISTFILE="$HOME/.zsh_history"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source $SPELLS/spells.init

for init_file in $(find $DOTFILES -type f -name "*.init" | sort); do
  source $init_file
done

for module in $(ls $DOTFILES/home/programs/zsh/*.zsh | sort); do
  source $module
done

# go to working directory if it has one
gtwd

# start typing + [Up-Arrow] - fuzzy find history forward
if [[ "${terminfo[kcuu1]}" != "" ]]; then
  autoload -U up-line-or-beginning-search
  zle -N up-line-or-beginning-search
  bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
fi
# start typing + [Down-Arrow] - fuzzy find history backward
if [[ "${terminfo[kcud1]}" != "" ]]; then
  autoload -U down-line-or-beginning-search
  zle -N down-line-or-beginning-search
  bindkey "${terminfo[kcud1]}" down-line-or-beginning-search
fi

# () {
# function prompt_mise() {
#   local plugins=("${(@f)$(mise current | grep -v "system" 2>/dev/null)}")
#   local plugin
#   for plugin in ${(k)plugins}; do
#     local parts=("${(@s/ /)plugin}")
#     local tool=${(U)parts[1]}
#     local version=${parts[2]}
#     p10k segment -r -i "${tool}_ICON" -s $tool -t "$version"
#   done
# }
# typeset -g POWERLEVEL9K_MISE_FOREGROUND=66
# typeset -g POWERLEVEL9K_MISE_DOTNET_CORE_FOREGROUND=134
# typeset -g POWERLEVEL9K_MISE_ELIXIR_FOREGROUND=129
# typeset -g POWERLEVEL9K_MISE_ERLANG_FOREGROUND=125
# typeset -g POWERLEVEL9K_MISE_FLUTTER_FOREGROUND=38
# typeset -g POWERLEVEL9K_MISE_GOLANG_FOREGROUND=37
# typeset -g POWERLEVEL9K_MISE_HASKELL_FOREGROUND=172
# typeset -g POWERLEVEL9K_MISE_JAVA_FOREGROUND=32
# typeset -g POWERLEVEL9K_MISE_JULIA_FOREGROUND=70
# typeset -g POWERLEVEL9K_MISE_LUA_FOREGROUND=32
# typeset -g POWERLEVEL9K_MISE_NODEJS_FOREGROUND=70
# typeset -g POWERLEVEL9K_MISE_PERL_FOREGROUND=67
# typeset -g POWERLEVEL9K_MISE_PHP_FOREGROUND=99
# typeset -g POWERLEVEL9K_MISE_POSTGRES_FOREGROUND=31
# typeset -g POWERLEVEL9K_MISE_PYTHON_FOREGROUND=37
# typeset -g POWERLEVEL9K_MISE_RUBY_FOREGROUND=168
# typeset -g POWERLEVEL9K_MISE_RUST_FOREGROUND=37
# # Substitute the default asdf prompt element
# typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=("${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]/asdf/mise}")
# }

export PATH="$HOME/.local/bin:$PATH"
