#              _
#             | |
#      _______| |__  _ __ ___
#     |_  / __| '_ \| '__/ __|
#    _ / /\__ \ | | | | | (__
#   (_)___|___/_| |_|_|  \___|

export DOTFILES="$HOME/.dotfiles"
export PATH=$PATH:$HOME/.spells:$HOME/.spells/git

source $DOTFILES/zsh/plugins.zsh
source $DOTFILES/zsh/theme.zsh
source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/functions.zsh

source $DOTFILES/haskell/haskell.init

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

