name: CI
on: [push, pull_request]
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check --all-systems
